name: flutter_gp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  device_info_plus: ^9.1.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_quill: ^9.3.0
  flutter_svg: ^2.0.10+1
  intl: ^0.18.1
 
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  stopwordies: ^1.0.1
  super_clipboard: ^0.8.5
  text_analysis: ^1.0.0+2
  tflite_flutter: ^0.10.4
  tflite_text_classification: ^0.0.2
  tflite_v2: ^1.0.0
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/stable_model.tflite
    - assets/model_24.tflite
    - assets/vocabulary.txt
    - assets/emojis/neutral.svg
    - assets/emojis/joy.svg
    - assets/emojis/sad.svg
    - assets/emojis/angry.svg
    - assets/emojis/surprised.svg
    - assets/emojis/fear.svg
    - assets/emojis/love.svg
