name: flutter_gp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  device_info_plus: ^9.1.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_quill: ^9.3.0
  intl: ^0.18.1
 
  path: ^1.9.0
  path_provider: ^2.1.2
  provider: ^6.1.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3
  super_clipboard: ^0.8.5
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
